server {
  listen 80;
  server_name _;
  root /var/www/html;
  index testar.html;

  location = /_waf_check {
    internal;
    proxy_pass http://model:8000/check;
    proxy_method POST;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-Method $request_method;
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header X-Original-Body-Length $content_length;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/ {
    auth_request /_waf_check;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    fastcgi_param SCRIPT_NAME /index.php;
    fastcgi_pass php:9000;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
